package consts

const TemplatePbEntityMessageContent = `
// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

syntax = "proto3";

package {PackageName};

{OptionContent}

{EntityMessage}

{ComplexEntityMessage}

option go_package = "./Model/PBEntity;{PackageName}";
`
